name: DEPLOY
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.0
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /home/nsbp8345/public_html
        remote_host: nsbpecangaan.com
        remote_user: nsbp8345
        remote_key: ${{ secrets.DEPLOY_KEY }}
